spring.application.name=warehouse-monitor

warehouse.udp-enabled=true

warehouse.udp.temperature-port=3344
warehouse.udp.humidity-port=3355

warehouse.threshold.temperature=35.0
warehouse.threshold.humidity=50.0

management.endpoints.web.exposure.include=health,info